server:
  port: 8500

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路由，注意这里是一个列表
      routes:
      - id: borrow-service  # 路由名称
        uri: lb://borrowservice # 路由的地址，lb表示使用负载均衡到服务，也可以使用http正常转发
        predicates: # 路由规则，断言什么请求会被路由
        - Path=/borrow/** # 只要是访问这个路径，一律都被路由到上面指定的服务
      - id: book-service
        uri: lb://bookservice
        predicates:
        - Path=/book/**
        filters:  # 添加过滤器
        - AddRequestHeader=Test, HelloWorld!  # AddRequestHeader 就是添加请求头信息

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7000/eureka, http://eureka02:7001/eureka